server:
  port: ${PORT:8091}

spring:
  http:
      converters:
        preferred-json-mapper: gson
  gson:
    pretty-printing: true
  application:
    name: config-server
  datasource:
    url: jdbc:mysql://tarjeticstore.ckkrkxfrt10h.us-east-1.rds.amazonaws.com:3306/bd_tarjetic?useSSL=false
    username: admin
    password: giacia12
    testWhileIdle: true
    validationQuery: SELECT 1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springboot-examples/spring-cloud
          #username: tavo.tf@gmail.com
          #password: 123456

config:
  key: dev

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.mlorenzo: 'DEBUG'